name: 'avenoirel'
version: '1.0.0'
profile: 'avenoirel'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  env: "{{ env_var('DBT_ENV', 'dev') }}"

models:
  avenoirel:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
    marts:
      +schema: marts
      +materialized: table
      revenue:
        +materialized: table
      loyalty:
        +materialized: table
      operations:
        +materialized: table
      core:
        +materialized: table